// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWENnN3F9tgSqCCqVfy-qSXrKZQLYud8s',
    appId: '1:215025848873:web:a1cdc5e1af51cdb6480238',
    messagingSenderId: '215025848873',
    projectId: 'ecommerce-firebase-4dbcf',
    authDomain: 'ecommerce-firebase-4dbcf.firebaseapp.com',
    storageBucket: 'ecommerce-firebase-4dbcf.firebasestorage.app',
    measurementId: 'G-F8RW8YM694',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aOjeF3eKgxFTmBiUDG2tvo-FrGE2HiQ',
    appId: '1:215025848873:android:288e20054bd4f65a480238',
    messagingSenderId: '215025848873',
    projectId: 'ecommerce-firebase-4dbcf',
    storageBucket: 'ecommerce-firebase-4dbcf.firebasestorage.app',
  );
}
